/** @type {import('tailwindcss').Config} */
module.exports = {
  // Fichiers scannés pour repérer les classes Tailwind utilisées (purge automatique).
  content: [
    "./app/templates/**/*.html",
    "./app/static/js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Palette industrielle Neemba / CAT — jaune logo unifié à #ffcd00
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed-dim": "#cdc4c5",
        "on-primary-fixed": "#000000",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#0d1c2e",
        "inverse-surface": "#000000",
        "error-container": "#ffdad6",
        "tertiary": "#515f74",
        "on-tertiary-container": "#4d5b70",
        "on-secondary-fixed": "#1e1b1c",
        "on-background": "#000000",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "primary": "#ffcd00",
        "on-primary-fixed-variant": "#000000",
        "secondary-fixed": "#e9e0e1",
        "primary-fixed-dim": "#ffcd00",
        "on-surface": "#000000",
        "tertiary-fixed": "#d5e3fc",
        "outline-variant": "#d4d4d4",
        "on-surface-variant": "#555555",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffcd00",
        "outline": "#888888",
        "error": "#ba1a1a",
        "on-primary-container": "#000000",
        "on-tertiary": "#ffffff",
        "on-primary": "#000000",
        "surface-container-high": "#e6e8ea",
        "secondary": "#635d5e",
        "surface-container": "#eceef0",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#000000",
        "surface": "#f7f9fb",
        "on-secondary-fixed-variant": "#4b4546",
        "secondary-container": "#e9e0e1",
        "primary-container": "#ffcd00",
        "on-secondary-container": "#696364",
        "on-tertiary-fixed-variant": "#3a485b",
        "tertiary-fixed-dim": "#b9c7df",
        "tertiary-container": "#c5d4ec",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#ffcd00",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xl: "80px",
        gutter: "24px",
        lg: "48px",
        md: "24px",
        base: "8px",
        "max-width-desktop": "1280px",
        sm: "12px",
        "margin-mobile": "16px",
        xs: "4px",
      },
      fontFamily: {
        "headline-lg": ["Archivo Narrow"],
        "body-md": ["IBM Plex Sans"],
        "label-bold": ["IBM Plex Sans"],
        "headline-md": ["Archivo Narrow"],
        "headline-lg-mobile": ["Archivo Narrow"],
        "headline-xl": ["Archivo Narrow"],
        "body-lg": ["IBM Plex Sans"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  // Plugins inclus nativement dans le CLI standalone (pas besoin d'npm install).
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
