/** @type {import('tailwindcss').Config} */
module.exports = {
  // Fichiers scannés pour repérer les classes Tailwind utilisées (purge automatique).
  content: [
    "./app/templates/**/*.html",
    "./app/static/js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Palette industrielle LiuGong — navy #0B2C6E (identité) + orange #EC6606 (accent)
        "primary-tint": "#fdeee1",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed-dim": "#c7ced8",
        "on-primary-fixed": "#0b2c6e",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#0d1c2e",
        "inverse-surface": "#0b2c6e",
        "error-container": "#ffdad6",
        "tertiary": "#3b5a8a",
        "on-tertiary-container": "#2a3e5c",
        "on-secondary-fixed": "#1b2026",
        "on-background": "#000000",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "primary": "#0b2c6e",
        "on-primary-fixed-variant": "#0b2c6e",
        "secondary-fixed": "#dce1e8",
        "primary-fixed-dim": "#ec6606",
        "on-surface": "#000000",
        "tertiary-fixed": "#d6e2f5",
        "outline-variant": "#d4d4d4",
        "on-surface-variant": "#555555",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ec6606",
        "outline": "#888888",
        "error": "#ba1a1a",
        "on-primary-container": "#0b2c6e",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "secondary": "#55606e",
        "surface-container": "#eceef0",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#0b2c6e",
        "surface": "#f7f9fb",
        "on-secondary-fixed-variant": "#454f59",
        "secondary-container": "#dce1e8",
        "primary-container": "#ec6606",
        "on-secondary-container": "#3c4650",
        "on-tertiary-fixed-variant": "#2c4468",
        "tertiary-fixed-dim": "#aec3e3",
        "tertiary-container": "#d6e2f5",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#ec6606",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
      },
      borderRadius: {
        DEFAULT: "0.625rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.875rem",
        xl: "1.25rem",
        "2xl": "1.75rem",
        full: "9999px",
      },
      boxShadow: {
        soft: "0 2px 10px rgba(11, 44, 110, 0.08)",
        card: "0 6px 20px rgba(11, 44, 110, 0.10)",
        lift: "0 14px 30px rgba(11, 44, 110, 0.18)",
        "glow-orange": "0 0 0 4px rgba(236, 102, 6, 0.18)",
        "glow-navy": "0 0 0 4px rgba(11, 44, 110, 0.15)",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      spacing: {
        xl: "80px",
        gutter: "24px",
        lg: "48px",
        md: "24px",
        base: "8px",
        "max-width-desktop": "1280px",
        sm: "12px",
        "margin-mobile": "16px",
        xs: "4px",
      },
      fontFamily: {
        "headline-lg": ["Archivo Narrow"],
        "body-md": ["IBM Plex Sans"],
        "label-bold": ["IBM Plex Sans"],
        "headline-md": ["Archivo Narrow"],
        "headline-lg-mobile": ["Archivo Narrow"],
        "headline-xl": ["Archivo Narrow"],
        "body-lg": ["IBM Plex Sans"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  // Plugins inclus nativement dans le CLI standalone (pas besoin d'npm install).
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
